name: WebOS build
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TOOLCHAIN_URL: https://github.com/openlgtv/buildroot-nc4/releases/latest/download/arm-webos-linux-gnueabi_sdk-buildroot.tar.gz
  TOOLCHAIN_DIR: /opt/arm-webos-linux-gnueabi_sdk-buildroot
  TOOLCHAIN_ENV_FILE: /opt/arm-webos-linux-gnueabi_sdk-buildroot/environment-setup
  TOOLCHAIN_FILE: /opt/arm-webos-linux-gnueabi_sdk-buildroot/share/buildroot/toolchainfile.cmake
  BUILD_DIR: build

jobs:
  build_ipk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Download and unpack toolchain
        working-directory: /opt
        run: |
          wget -q -O toolchain.tar.gz ${TOOLCHAIN_URL}
          tar xf toolchain.tar.gz

      - name: Relocate toolchain
        run: |
          pushd ${TOOLCHAIN_DIR}
          ./relocate-sdk.sh
          popd

      - name: Install native dependencies
        env:
          apt_deps: cmake build-essential
        run: |
          sudo apt update
          sudo apt install -y ${{ env.apt_deps }}

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - run: npm ci
      - run: npm run lint
      - run: npm run build -- --env production
      - name: Build service
        run: |
          mkdir -p ./dist/service
          rm -rf ./dist/service/*
          mkdir -p ./service/build
          pushd service/build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
          make
          popd
          cp -r ./service/build/dist/* ./dist/service/

      - name: Ensure executables +x
        run: |
          chmod +x ./dist/service/testapp

      - run: npm run package
      - run: npm run gen-manifest

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: testapp-ipk
          path: |
            ${{github.workspace}}/*.ipk

      - uses: marvinpinto/action-automatic-releases@latest
        if: "github.ref == 'refs/heads/master'"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: "Development Build"
          files: |
            ${{github.workspace}}/*.ipk
            ${{github.workspace}}/org.webosbrew.testapp.manifest.json

      - uses: marvinpinto/action-automatic-releases@latest
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{ github.ref_name }}
          files: |
            ${{github.workspace}}/*.ipk
            ${{github.workspace}}/org.webosbrew.testapp.manifest.json
